const SearchActionTypes = {
  SET_SEARCH_TERM: "SET_SEARCH_TERM",
  SET_SEARCH_TYPE: "SET_SEARCH_TYPE",
  SPEECH_MODAL_HIDDEN: "SPEECH_MODAL_HIDDEN",
  APPS_DROPDOWN_HIDDEN: "APPS_DROPDOWN_HIDDEN",
  ACCOUNT_DROPDOWN_HIDDEN: "ACCOUNT_DROPDOWN_HIDDEN",
};

export default SearchActionTypes;
